name: android-studio-canary
adopt-info: android-studio-canary
summary: The IDE for Android (Canary build)
description: |
  Android Studio provides the fastest tools for building apps on every type
  of Android device.

  World-class code editing, debugging, performance tooling, a flexible build
  system, and an instant build/deploy system all allow you to focus on
  building unique and high quality apps.
base: core18

grade: stable
confinement: classic
compression: lzo
architectures:
  - build-on: amd64

apps:
  android-studio-canary:
    command: android-studio/bin/studio.sh
    desktop: android-studio-canary.desktop

parts:
  desktop:
    plugin: dump
    source: https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2025.1.1.9/android-studio-2025.1.1.9-linux.tar.gz
    prime:
      - android-studio-canary.desktop
  android-studio-canary:
    after: [desktop]
    plugin: nil
    override-build: |
      snapcraftctl build
      echo "Get latest release..."
      RELEASE_INFO=$(python3 -u $SNAPCRAFT_STAGE/get_latest.py)

      # Download
      DOWNLOAD_URL=$(echo ${RELEASE_INFO} | cut -d ' ' -f2)
      wget --quiet "${DOWNLOAD_URL}" -O "${SNAPCRAFT_PART_INSTALL}/android-studio.tgz"
      tar zxvf "${SNAPCRAFT_PART_INSTALL}/android-studio.tgz" -C "${SNAPCRAFT_PART_INSTALL}"

      # Cleanup
      rm "${SNAPCRAFT_PART_INSTALL}/android-studio.tgz"

      # Set version
      snapcraftctl set-version $(echo $RELEASE_INFO | cut -d ' ' -f1)
    build-packages:
      - wget
      - python3
      - python3-bs4
    build-attributes:
      - no-patchelf
